spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${SPRING_JDBC_HOST:localhost}:${SPRING_JDBC_PORT:3306}/dbcompany?createDatabaseIfNotExist=true&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 6316
  main:
    banner-mode: "off"
